engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    exclude_fingerprints:
    - 42b4b225a9c6cf44b27182f397e2b7ad # REMOVE this one when replacing with something useful
    checks:
      CyclomaticComplexity:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      Design/TooManyMethods:
        enabled: false
      Design/NpathComplexity:
        enabled: false
      Design/WeightedMethodCount:
        enabled: false
      Design/LongClass:
        enabled: false
      Controversial/CamelCaseMethodName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Naming/ShortVariable:
        enabled: false
      CleanCode/ElseExpression:
        enabled: false
      Design/LongMethod:          # sometimes we have longer methods than 100 rows
        enabled: false
  radon:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- docs/**
- tests/**
- vendor/**
